# Generated by Django 5.2.6 on 2025-09-16 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(default='Unit', max_length=64)),
                ('ratio', models.FloatField(default=1.0)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('product_type', models.CharField(choices=[('stockable', 'Stockable Product'), ('consumable', 'Consumable'), ('service', 'Service')], default='stockable', max_length=16)),
                ('list_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uom_templates', to='inventory.unitofmeasure')),
                ('uom_po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uom_po_templates', to='inventory.unitofmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('list_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute_values', models.ManyToManyField(related_name='variants', to='inventory.productattributevalue')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.producttemplate')),
            ],
        ),
    ]
